# Generated by Django 5.2.1 on 2025-06-08 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUnidadAcademica',
            fields=[
                ('tipo_unidad_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Unidad Académica',
                'verbose_name_plural': 'Tipos de Unidades Académicas',
            },
        ),
        migrations.AlterField(
            model_name='carreramaterias',
            name='ciclo_sugerido',
            field=models.IntegerField(blank=True, help_text='Número de ciclo sugerido para la materia (1, 2, 3...)', null=True),
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('ciclo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ciclo', models.CharField(max_length=100)),
                ('orden', models.IntegerField(help_text='Orden numérico para los ciclos (ej: 1, 2, 3...)', unique=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos', to='academic_setup.carrera')),
            ],
            options={
                'verbose_name': 'Ciclo',
                'verbose_name_plural': 'Ciclos',
                'ordering': ['orden'],
                'unique_together': {('nombre_ciclo', 'carrera')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='carreramaterias',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='carreramaterias',
            name='ciclo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materias_carrera_asignadas', to='academic_setup.ciclo'),
        ),
        migrations.AlterUniqueTogether(
            name='carreramaterias',
            unique_together={('carrera', 'materia', 'ciclo')},
        ),
        migrations.AddField(
            model_name='unidadacademica',
            name='tipo_unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_academicas', to='academic_setup.tipounidadacademica'),
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('seccion_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_seccion', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='academic_setup.ciclo')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'unique_together': {('nombre_seccion', 'ciclo')},
            },
        ),
    ]
