# Generated by Django 5.2.1 on 2025-05-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docentes',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
