# Generated by Django 5.2.1 on 2025-05-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupos',
            name='ciclo_semestral',
            field=models.IntegerField(blank=True, help_text='Ciclo académico al que pertenece este grupo/materia (ej. 1, 2, ..., 10)', null=True),
        ),
    ]
