# Generated by Django 5.2.1 on 2025-06-18 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_setup', '0003_alter_ciclo_unique_together_alter_ciclo_orden_and_more'),
        ('scheduling', '0002_grupos_ciclo_semestral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupos',
            name='materia',
        ),
        migrations.AddField(
            model_name='grupos',
            name='materias',
            field=models.ManyToManyField(related_name='grupos', to='academic_setup.materias'),
        ),
        migrations.AddField(
            model_name='horariosasignados',
            name='materia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clases_asignadas', to='academic_setup.materias'),
        ),
    ]
