# Generated by Django 5.2.1 on 2025-06-18 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_setup', '0003_alter_ciclo_unique_together_alter_ciclo_orden_and_more'),
        ('scheduling', '0003_remove_grupos_materia_grupos_materias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupos',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_carrera', to='academic_setup.carrera'),
        ),
        migrations.AlterField(
            model_name='grupos',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_periodo', to='academic_setup.periodoacademico'),
        ),
    ]
